---
layout: page
title: 
group: navigation
permalink: "publications.html"
---
{% include JB/setup %}

<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>

Publications
------------------------

For a full list see: <a href="http://www.ncbi.nlm.nih.gov/pubmed?term=%22Buenrostro%20J%22%5BAuthor%5D%20OR%20%22Buenrostro%20JD%22%5BAuthor%5D" target="_blank">PubMed</a> or <a href="https://scholar.google.com/citations?user=M9sejPIAAAAJ&hl=en" target="_blank">Google Scholar</a>

<b>SELECTED PUBLICATIONS
1. Lal A\*, <b>Chiang ZD</b>\*, Yakovenko N, <b>Duarte FM</b>, Israeli J☨, <b>Buenrostro JD</b>☨.  <a href="https://www.biorxiv.org/content/10.1101/829481v1" target="_blank">AtacWorks: A deep convolutional neural network toolkit for epigenomics</a>. bioRxiv (2019).<br>
2. <b>Lareau C</b>☨, <b>Ma S</b>, <b>Duarte F</b>, <b>Buenrostro JD</b>☨.  <a href="https://www.biorxiv.org/content/10.1101/824003v2.abstract" target="_blank">Inference and effects of barcode multiplets in droplet-based single-cell assays</a>. bioRxiv (2019). (☨co-corresponding)<br>
1. <b>Lareau CA</b>\*, <b>Duarte FM</b>\*, Chew JG\*, <b>Kartha VK</b>, Burkett ZD, Kolhway AS, Pokholok D, Aryee MJ, Steemers FJ, Lebofsky R☨, <b>Buenrostro JD☨</b>. <a href="https://www.nature.com/articles/s41587-019-0147-6" target="_blank">Droplet-based combinatorial indexing for massive-scale single-cell chromatin accessibility</a>. Nature Biotechnology (2019).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•  Featured in <a href="https://news.harvard.edu/gazette/story/2019/06/new-atac-seq-method-from-harvard-accelerates-single-cell-research/" target="_blank"> The Harvard Gazette </a> <a href="https://www.nature.com/nbt/journal/v34/n11/full/nbt.3724.html" target="_blank">
1. Ulirsch JC\*, <b>Lareau CA</b>\*, Bao EL\*, Ludwig LS, Guo MH, Benner C, Satpathy AT, <b>Kartha VK</b>, Salem R, Hirschhorn JN, Finucane HK, Aryee MJ, <b>Buenrostro JD☨</b>, Sankaran VG☨. <a href="https://www.nature.com/articles/s41588-019-0362-6" target="_blank">Interrogation of human hematopoiesis at single-cell and single-variant resolution</a>. Nature Genetics (2019).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•  Featured in <a href="https://www.nature.com/articles/s41588-019-0386-y" target="_blank"> Nature Genetics </a> 
2. Yoshida H, <b>Lareau CA</b>, Ramirez RN, Rose SA, Maier B, Wroblewska A, Desland F, Chudnovskiy A, Mortha A, Dominguez C, Tellier J, Kim E, Dwyer D, Shinton S, Nabekura T, Qi Y, Yu B, Robinette M, Kim K, Wagers A, Rhoads A, Nutt SL, Brown BD, Mostafavi S☨, <b>Buenrostro JD☨</b>, Benoist C☨, the Immunological Genome Project. <a href="https://www.cell.com/cell/fulltext/S0092-8674(18)31650-7" target="_blank">The cis-Regulatory Atlas of the Mouse Immune System</a>. Cell (2019).
3. Shema E, Bernstein BE, <b>Buenrostro JD</b>. <a href="https://www.nature.com/articles/s41588-018-0290-x" target="_blank">Single-cell and single-molecule epigenomics to uncover genome regulation at unprecedented resolution</a>. Nature Genetics (2018).
4. <b>Buenrostro JD</b>☨, Corces R, <b>Lareau C</b>, Wu B, Schep AN, Aryee MJ, Majeti R, Chang HY, Greenleaf WJ☨. <a href="https://www.cell.com/cell/abstract/S0092-8674(18)30446-X" target="_blank">Integrated Single-Cell Analysis Maps the Continuous Regulatory Landscape of Human Hematopoietic Differentiation</a>. Cell (2018).
5. Satpathy AT\*, Saligrama N\*, <b>Buenrostro JD</b>\*, Wei Y, Wu B, Rubin AJ, Granja JM, Li R, Mumbach MR, <b>Lareau CA</b>, Serratelli WS, Gennert DG, Schep AN, Corces MR, Kim YH, Khavari PA, Greenleaf WJ, Davis MM, Chang HY. <a href="https://www.nature.com/articles/s41591-018-0008-8" target="_blank">Transcript-indexed ATAC-seq for precision immune profiling</a>. Nature Medicine (2018).
6. Schep AN, Wu B, <b>Buenrostro JD</b>☨, Greenleaf WJ☨. <a href="http://www.nature.com/nmeth/journal/vaop/ncurrent/full/nmeth.4401.html" target="_blank">chromVAR: inferring transcription-factor-associated accessibility from single-cell epigenomic data</a>. Nature Methods (2017).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•  Top 10 paper to read in <a href="https://www.iscb.org/recomb-regsysgen2017-submissions/recomb-regsysgen2017-top-10-papers-reading-list" target="_blank">RECOMB/ISCB</a>
4. Corces MR\* & <b>Buenrostro JD</b>\*☨, Wu B, Greenside PG, Chan SM, Koenig JL, Snyder MP, Pritchard JK, Kundaje A, Greenleaf WJ, Majeti R+, Chang HY+. <a href="http://www.nature.com/ng/journal/v48/n10/full/ng.3646.html" target="_blank">Lineage-specific and single cell chromatin accessibility charts human hematopoiesis and leukemia evolution</a>. Nature Genetics (2016).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•  Featured in <a href="https://www.nature.com/nbt/journal/v34/n11/full/nbt.3724.html" target="_blank"> Nature Biotech</a>
5. <b>Buenrostro JD</b>, Wu B, Litzenburger U, Gonzales M, Ruff D, Snyder M, Chang HY, Greenleaf WJ. <a href="http://www.nature.com/nature/journal/v523/n7561/full/nature14590.html" target="_blank">Single-cell chromatin accessibility reveals principles of regulatory variation</a>. Nature (2015).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•  Featured in <a href="https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0737-7" target="_blank">Genome Biol.</a> and <a href="https://www.nature.com/articles/nmeth.3503" target="_blank">Nature Methods</a>.
6. Schep AN, <b>Buenrostro JD</b>, Denny SK, Schwartz K, Sherlock G, Greenleaf WJ. <a href="http://genome.cshlp.org/content/25/11/1757.full" target="_blank">Structured nucleosome fingerprints enable high-resolution mapping of chromatin architecture within regulatory regions</a>. Genome Research (2015).
7. <b>Buenrostro JD</b>\* & Araya CL\*, Chircus LM, et al. <a href="http://www.nature.com/nbt/journal/v32/n6/abs/nbt.2880.html" target="_blank">Quantitative analysis of RNA-protein interactions on a massively parallel array reveals biophysical and evolutionary landscapes</a>. Nature Biotechnology (2014).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•  Selected as the <a href="http://www.nature.com/nbt/journal/v32/n6/covers/index.html" target="_blank">cover</a> for Nature Biotechnology and featured in <a href="http://www.nature.com/nmeth/journal/v11/n6/full/nmeth.2985.html" target="_blank">Nature Methods</a>
8. <b>Buenrostro JD</b>, Giresi PG, Zaba LC, Chang HY, Greenleaf WJ. <a href="http://www.nature.com/nmeth/journal/v10/n12/abs/nmeth.2688.html" target="_blank">Transposition of native chromatin for fast and sensitive epigenomic profiling of open chromatin, DNA-binding proteins and nucleosome position</a>. Nature Methods (2013).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•  Featured in <a href="http://www.nature.com/nmeth/journal/v11/n1/full/nmeth.2770.html" target="_blank">Nature Methods</a> and voted most influential paper by <a href="https://www.iscb.org/recomb-regsysgen2014-submissions/recomb-regsysgen2014-top-ten-papers" target="_blank"> RECOMB/ISCB</a>
9. Carpenter ML, <b>Buenrostro JD</b>, Valdiosera C, et al. <a href="http://www.sciencedirect.com/science/article/pii/S000292971300459X" target="_blank">Pulling out the 1%: Whole-Genome Capture for the Targeted Enrichment of Ancient DNA Sequencing Libraries</a>. The American Journal of Human Genetics (2013).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;•  Featured in <a href="http://science.sciencemag.org/content/342/6158/543.full" target="_blank"> Science </a> and <a href="http://www.nature.com/ng/journal/v45/n12/full/ng.2842.html" target="_blank"> Nature Genetics </a>
10. Myllykangas S\* & <b>Buenrostro JD</b>\*, Natsoulis G, Bell JM, Ji HP. <a href="http://www.nature.com/nbt/journal/v29/n11/full/nbt.1996.html" target="_blank">Efficient targeted resequencing of human germline and cancer genomes by oligonucleotide-selective sequencing</a>. Nature Biotechnology (2011).<br>
(\*equal contribution) (☨co-corresponding)<br>

<b>ADDITIONAL PUBLICATIONS
12. Chen H, Albergante L, Hsu JY, <b>Lareau CA</b>, Lo Bosco G, Guan J, Zhou S, Gorban AN, Bauer DE, Aryee MJ, Langenau DM, Zinovyev A, <b>Buenrostro JD</b>, Yuan GC, Pinello L. <a href="https://www.nature.com/articles/s41467-019-09670-4" target="_blank">Single-cell trajectories reconstruction, exploration and mapping of omics data with STREAM</a>. Nature Communications (2019).
12. Ludwig LS, <b>Lareau CA</b>, Ulirsch JC, Christian E, Muus C, Li LH, Pelka K, Ge W, Oren Y, <b>Brack A</b>, Law T, Rodman C, Chen JH, Boland GM, Hacohen N, Rozenblatt-Rosen O, Aryee MJ, <b>Buenrostro JD</b>, Regev A, Sankaran VG. <a href="https://www.sciencedirect.com/science/article/pii/S0092867419300558" target="_blank">Lineage Tracing in Humans Enabled by Mitochondrial Mutations and Single-Cell Genomics</a>. Cell (2019).
12. Zviran A, Mor N, Rais Y, Gingold H, Peles S, Chomsky E, Viukov S, <b>Buenrostro JD</b>, Scognamiglio R, Weinberger L, Manor YS, Krupalnik V, Zerbib M, Hezroni H, Jaitin DA, Larastiaso D, Gilad S, Benjamin S, Gafni O, Mousa A, Ayyash M, Sheban D, Bayerl J, Aguilera-Castrejon A, Massarwa R, Maza I, Hanna S, Stelzer Y, Ulitsky I, Greenleaf WJ, Tanay A, Trumpp A, Amit I, Pilpel Y, Novershtern N, Hanna JH. <a href="https://www.sciencedirect.com/science/article/pii/S1934590918305502" target="_blank">Deterministic Somatic Cell Reprogramming Involves Continuous Transcriptional Changes Governed by Myc and Epigenetic-Driven Modules</a>. Cell Stem Cell (2018).
11. Mor N, Rais Y, Sheban D, Peles S, Aguilera-Castrejon A, Zviran A, Elinger D, Viukov S, Geula S, Krupalnik V, Zerbib M, Chomsky E, Lasman L, Shani T, Bayerl J, Gafni O, Hanna S, <b>Buenrostro JD</b>, Hagai T, Masika, Vainorius G, Bergman Y, Greenleaf WJ, Esteban MA, Elling U, Levin Y, Massarwa R, Merbl Y, Novershtern N, Hanna JH. <a href="https://www.sciencedirect.com/science/article/pii/S1934590918303400" target="_blank">Neutralizing Gatad2a-Chd4-Mbd3/NuRD Complex Facilitates Deterministic Induction of Naive Pluripotency</a>. Cell Stem Cell (2018).
12. Chihara N, Madi A, Kondo T, Zhang H, Acharya N, Singer M, Nyman J, Marjanovic ND, Kowalczyk MS, Wang C, Kurtulus S, Law T, Etminan Y, Nevin J, Buckley CD, Burkett PR, <b>Buenrostro JD</b>, Rozenblatt-Rosen O, Anderson AC, Regev A, Kuchroo CK. <a href="https://www.nature.com/articles/s41586-018-0206-z" target="_blank">Induction and transcriptional regulation of the co-inhibitory gene module in T cells</a>. Nature (2018).
13. Finucane HK, Reshef YA, Anttila V, Slowikowski K, Gusev A, Byrnes A, Gazal S, Loh P, <b>Lareau C</b>, Shoresh N, Genovese G, Saunders A, Macosko E, Pollack S, The Brainstorm Consortium, Perry JRB, <b>Buenrostro JD</b>, Bernstein BE, Raychaudhuri S, McCarroll S, Neale BM, Price AL. <a href="https://www.nature.com/articles/s41588-018-0081-4" target="_blank">Heritability enrichment of specifically expressed genes identifies disease-relevant tissues and cell types</a>. Nature Genetics (2018).
10. Koh AS, Miller EL, <b>Buenrostro JD</b>, Moskowitz DM, Wang J, Greenleaf WJ, Chang HY, Crabtree WJ. <a href="https://www.nature.com/articles/s41590-017-0032-8" target="_blank">Rapid chromatin repression by Aire provides precise control of immune tolerance</a>. Nature Immunology (2018).
11. Daugherty AC, Yeo RW, <b>Buenrostro JD</b>, Greenleaf WJ, Kundaje A, Brunet A. <a href="http://genome.cshlp.org/content/27/12/2096.short" target="_blank">Chromatin accessibility dynamics reveal novel functional enhancers in C. elegans</a>. Genome Research (2017).
12. Soto-Feliciano YM, Bartlebaugh JME, Liu Y, Sánchez-Rivera FJ, Bhutkar A, Weintraub AS, <b>Buenrostro JD</b>, Cheng CS, Regev A, Jacks TE, Young RA, Hemann MT. <a href="http://genesdev.cshlp.org/content/early/2017/06/12/gad.295857.117.abstract" target="_blank">PHF6 regulates phenotypic plasticity through chromatin organization within lineage-specific genes</a>. Genes & Dev. (2017).
13. She R, Chakravarty AK, Layton CJ, Chircus LM, Andreasson JO, Damaraju N, McMahon PL, <b>Buenrostro JD</b>, Jarosz DF, Greenleaf WJ. <a href="http://www.pnas.org/content/114/14/3619.abstract" target="_blank">Comprehensive and quantitative mapping of RNA-protein interactions across a transcribed eukaryotic genome</a>. PNAS (2017).
14. Miller EL, Hargreaves DC, Kadoch C, Chang CY, Calarco JP, Hodges C, <b>Buenrostro JD</b>, Cui K, Greenleaf WJ, Zhao K, Crabtree GR. <a href="http://www.nature.com/nsmb/journal/v24/n4/full/nsmb.3384.html" target="_blank">TOP2 synergizes with BAF chromatin remodeling for both resolution and formation of facultative heterochromatin</a>. Nat Struct Mol Biol. (2017).
15. Moskowitz DM, Zhang DW, Hu B, Le Saux S, Yanes RE, Ye Z, <b>Buenrostro JD</b>, Weyand CM, Greenleaf WJ, Goronzy JJ. <a href="http://immunology.sciencemag.org/content/2/8/eaag0192" target="_blank">Epigenomics of human CD8 T cell differentiation and aging</a>. Science Immunology (2017).
16. Litzenburger UM, <b>Buenrostro JD</b>, Wu B, Shen Y, Sheffield NC, Kathiria A, Greenleaf WJ, Chang HY. <a href="https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1133-7" target="_blank">Single-cell epigenomic variability reveals functional cancer heterogeneity</a>. Genome Biol (2017).
17. Guo MH, Nandakumar SK, Ulirsch JC, Zekavat SM, <b>Buenrostro JD</b>, Natarajan P, Salem RM, Chiarle R, Mitt M, Kals M, Pärn K, Fischer K, Milani L, Mägi R, Palta P, Gabriel SB, Metspalu A, Lander ES, Kathiresan S, Hirschhorn JN, Esko T, Sankaran VG. <a href="http://www.pnas.org/cgi/pmidlookup?view=long&pmid=28031487" target="_blank">Comprehensive population-based genome sequencing provides insight into hematopoietic regulatory mechanisms</a>. PNAS (2017).
18. Chen X, Shen Y, Draper W, <b>Buenrostro JD</b>, Litzenburger U, Cho SW, Satpathy AT, Carter AC, Ghosh RP, East-Seletsky A, Doudna JA, Greenleaf WJ, Liphardt JT, Chang HY. <a href="http://www.nature.com/nmeth/journal/v13/n12/full/nmeth.4031.html" target="_blank">ATAC-see reveals the accessible genome by transposase-mediated imaging and sequencing</a>. Nature Methods (2016).
19. Mazumdar C, Shen Y, Xavy S, Zhao F, Reinisch A, Li R, Corces M R, Flynn R A, <b>Buenrostro JD</b>, Chan SM, Thomas D, Koenig JL, Hong WJ, Chang HY, Majeti R. <a href="http://www.cell.com/cell-stem-cell/abstract/S1934-5909(15)00424-5" target="_blank">Leukemia-Associated Cohesin Mutants Dominantly Enforce Stem Cell Programs and Impair Human Hematopoietic Progenitor Differentiation</a>. Cell Stem Cell (2015).
20. Maza I, Caspi I, Zviran A, Chmosky E, Rais Y, Viukov S, Geula S, <b>Buenrostro JD</b>, Weinberger L, Krupalnik V, Zerbib M, Dutton JR, Greenleaf WJ, Massarwa R, Novershtern N and Hanna JH. <a href="http://www.nature.com/nbt/journal/v33/n7/full/nbt.3270.html" target="_blank">Transient Acquisition of Pluripotency During Somatic Cell Transdifferentiation with iPSC Reprogramming Factors</a>. Nature Biotechnology (2015).
21. <b>Buenrostro JD</b>, Wu B, Chang HY, Greenleaf WJ. <a href="http://onlinelibrary.wiley.com/doi/10.1002/0471142727.mb2129s109/full" target="_blank">ATAC-seq: A method for Assaying Chromatin Accessibility Genome-wide</a>. Curr. Protoc. Mol. Biol. (2015).
22. Couthouis J, Raphael AR, Siskind C, Findlay AR, <b>Buenrostro JD</b>, Greenleaf WJ, et al. <a href="http://www.sciencedirect.com/science/article/pii/S0960896614000479" target="_blank">Exome sequencing identifies a DNAJB6 mutation in a family with dominantly-inherited limb-girdle muscular dystrophy</a>. Neuromuscular Disorders (2014).
23. Myllykangas S, <b>Buenrostro J</b>, Ji HP. <a href="https://link.springer.com/chapter/10.1007%2F978-1-4614-0782-9_2" target="_blank">Overview of Sequencing Technology Platforms</a>.  Rodriguez-Expeleta N, Hackenberg M, Aransay A, Bioinformatics for High Throughput Sequencing. p11-26. Springer (2012).
24. Flaherty P, Natsoulis G, Muralidharan O, Winters M, <b>Buenrostro J</b>, Bell J, et al. <a href="https://academic.oup.com/nar/article-lookup/doi/10.1093/nar/gkr861" target="_blank">Ultrasensitive detection of rare mutations using next-generation targeted resequencing</a>. Nucleic Acids Res (2012).
25. Natsoulis G, Bell JM, Xu H, <b>Buenrostro JD</b>, Ordonez H, et al. <a href="http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0021088" target="_blank">A Flexible Approach for Highly Multiplexed Candidate Gene Targeted Resequencing</a>. PLoS ONE (2011).
26. Dick CA, <b>Buenrostro J</b>, Butler T, Carlson ML, Kliebenstein DJ, Whittall JB. <a href="http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0018230" target="_blank">Arctic Mustard Flower Color Polymorphism Controlled by Petal-Specific Downregulation at the Threshold of the Anthocyanin Biosynthetic Pathway</a>. PLoS ONE (2011).
27. Whittall JB, Syring J, Parks M, <b>Buenrostro J</b>, Dick C, Liston A, Cronn R. <a href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-294X.2009.04474.x/full" target="_blank">Finding a (pine) needle in a haystack: chloroplast genome sequence divergence in rare and widespread pines</a>. Molecular Ecology (2010).

<b>PATENTS
1. Chang HY, Greenleaf WJ, Xingqi Chen, <b>Buenrostro JD</b>. <a href="https://patents.google.com/patent/WO2017156336A1" target="_blank">Transposase-mediated imaging of the accessible genome</a> (2017).
2. Giresi P, <b>Buenrostro JD</b>, Chang HY, Greenleaf WJ. <a href="https://www.google.com/patents/US20160060691" target="_blank">Transposition of Native Chromatin for Personal Epigenomics</a> (2013).
3. Bustamante CD, Carpenter ML, <b>Buenrostro JD</b>, Greenleaf WJ. <a href="https://www.google.com/patents/US20150360194" target="_blank">Enrichment of DNA Sequencing Libraries from Samples Containing Small Amounts of Target DNA</a> (2013).
4. Myllykangas S, <b>Buenrostro JD</b>, Ji HP. <a href="https://www.google.com/patents/US9309556" target="_blank">Direct Capture, Amplification and Sequencing of Target DNA Using Immobilized Primers</a> (2010).
